DROP TABLE IF EXISTS viesti_kayttaja RESTRICT;
DROP TABLE IF EXISTS viesti RESTRICT;
DROP TABLE IF EXISTS viestiketju RESTRICT;
DROP TABLE IF EXISTS aihe RESTRICT;
DROP TABLE IF EXISTS kayttaja RESTRICT;
